BASE_DOMAIN_URL = "https://www.saucedemo.com/"
USERNAME = "*[data-test=\"username\"]"
PASSWORD = "*[data-test=\"password\"]"
USERNAME_ID = "standard_user"
WRONG_USERNAME_ID = "locked_out_user"
PASSWORD_ID = "secret_sauce"
LOGIN_BUTTON = "*[data-test=\"login-button\"]"
ERROR_TEXT = "*[data-test=\"error\"]"
ERROR_TEXT_MESSAGE = "Epic sadface: Sorry, this user has been locked out."

INVENTORY_ITEM = "inventory_item"
INVENTORY_ITEM_NAME = "inventory_item_name"
PRODUCT_SORT = "*[data-test=\"product_sort_container\"]"
PRODUCT_SORT_Z2A = "//*[@id=\"header_container\"]/div[2]/div[2]/span/select/option[2]"
PRODUCT_SORT_L2H = "//*[@id=\"header_container\"]/div[2]/div[2]/span/select/option[3]"
PRODUCT_NAMES = "data/productNames.xlsx"
PRODUCTS_ON_BASKET = "data/addBasketFromExcel.xlsx"
FIRST_PAGE = "Sheet1"
FIRST_PRODUCT = "Sauce Labs Bike Light"
SECOND_PRODUCT = "Sauce Labs Onesie"
FIRST_PRODUCT_ID = "add-to-cart-sauce-labs-bike-light"
SECOND_PRODUCT_ID = "add-to-cart-sauce-labs-onesie"
BASKET_LINK = "shopping_cart_link"
CHECK_BASKET_PRODUCTS = "shopping_cart_badge"
REMOVE_PRODUCT = "//*[@id='remove-sauce-labs-bike-light']"
REMOVED_ITEM = "removed_cart_item"