BASE_DOMAIN_URL = "https://www.saucedemo.com/"
LOGIN_TEXT = "Giriş Yap"
LOGIN_BTN_XPATH="//*[@id='navbar']/div/div/div/ul/li[3]/a"
USER_NAME_ID="user-name"
PASSWORD_ID="password"
LOGIN_ID="login-button"
GIRIS_TITLE="title"
GIRIS_TITLE_XPATH="/html/body/div/div/div/div[1]/div[2]/span"
ERROR_MSJ = "error-message-container"
ERROR_MSJ_CONTAINER= "Epic sadface: Username and password do not match any user in this service"
PRODUCTNUMBER = "inventory_item"
BUTTONNAME="add-to-cart-sauce-labs-backpack"
REMOVEBTNNAME="remove-sauce-labs-backpack"
BASKETID="shopping_cart_container"
BASKETIDTEXT="1"